# Site settings
course_name: Computer Networks
course_description: "The principles and practice of computer networking, with emphasis on the Internet. The structure and components of computer networks, packet switching, layered architectures, TCP/IP, physical layer, error control, window flow control, local area networks (Ethernet, Token Ring; FDDI), network layer, congestion control, quality of service, multicast. Students enrolling in 244A Winter Quarter must have completed 140, or equivalent."
course_semester: "Fall 2024"

baseurl: "/cn-2024" # the subpath of your site, e.g. /blog/
url: "https://huangqy89.github.io/" # the base hostname & protocol for your site

schoolname: "Sun Yat-sen University"
schoolurl: "https://sysu.edu.cn"
# twitter_username: huangqy89

address: |
    No.132 Outer Ring East Road,
    Guangzhou Higher Education Mega Center,
    Guangzhou

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    experiments:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"

repository: huangqy89/cn-2024